package:
  name: matplotlib
  version: 3.6.0

patches:
  - setupext.patch

requirements:
  host:
    - freetype 2.9.1
    - libpng 1.6.34
    - numpy 1.26.0

  build:
    - certifi
    - setuptools_scm

# about:
#   license_file: LICENSE/LICENSE
