# This recipe doesn't work on Python 3.9 (due to setuptools_scm availability issues),
# or on Python 3.13 (due to numpy availability issues)
package:
  name: matplotlib
  version: 3.6.0

patches:
  - setupext.patch

requirements:
  host:
    - freetype 2.9.1
    - libpng 1.6.34
    - numpy 1.26.2

  build:
    - certifi
    - setuptools_scm
