package:
  name: Pillow
  version: 9.4.0

patches:
  - setup.patch

build:
  script_env:
    # libfreetype references both libz and libbz2
    # but doesn't link them into the static library
    - LDFLAGS=-lz -lbz2

requirements:
  host:
    # PNG support is internal: libpng is not used.
    - libjpeg 1.5.3
    - freetype 2.9.1
