package:
  name: cryptography
  version: 3.4.8

build:
  script_env:
    - CRYPTOGRAPHY_DONT_BUILD_RUST=1

requirements:
  build:
    - cffi 1.15.1
    - setuptools-rust 0.11.6
    # "setuptools_rust @ git+https://github.com/freakboy3742/setuptools_rust@iOS-support",
  host:
    - openssl 1.1.1v
    # - openssl 3.1.2
