package:
  name: cryptography
  version: 41.0.4

patches:
  - random.patch

build:
  script_env:
    - OPENSSL_STATIC=1
    - OPENSSL_DIR={platlib}/opt

requirements:
  build:
    - setuptools_rust @ git+https://github.com/freakboy3742/setuptools-rust@iOS-support
  host:
    - openssl 3.1.2
